name: Test Non-Main Branches

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run Unit Tests
        run: mvn test -Dtest=FilmServiceUnitTest
      - name: Run Integration Tests
        run: mvn test -Dtest=FilmServiceIntegrationTest
