name: Nightly Quality Assurance

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  multibrowser:
    name: multibrowser
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - browser: chrome
            os: ubuntu-latest
          - browser: firefox
            os: ubuntu-latest
          - browser: chrome
            os: macos-latest
          - browser: firefox
            os: macos-latest
          - browser: chrome
            os: windows-latest
          - browser: firefox
            os: windows-latest
          - browser: edge
            os: windows-latest
          - browser: safari
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Web system test [${{ matrix.browser }} / ${{ matrix.os }}]
        run: mvn test -Dtest="FilmServiceUnitTest,FilmServiceIntegrationTest" -Dbrowser=${{ matrix.browser }} -Dos=${{ matrix.os }}

  loadtesting:
    name: loadtesting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Run tests
        run: mvn test      
      - name: Extract project version
        id: get_version
        run: echo "version=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.get_version.outputs.version }}
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.get_version.outputs.version }}
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure (staging)
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name nitflex-staging \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.get_version.outputs.version }} \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_TOKEN }} \
            --ports 8080 \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5
            
      - name: Install Artillery
        run: npm install -g artillery
      - name: Run smoke test
        run: artillery run smoke-test.yml
      - name: Run load test
        run: artillery run load-test.yml

  release-nightly:
    name: Publicar artefacto nightly
    runs-on: ubuntu-latest
    needs: [multibrowser, loadtesting]
    steps:
      - uses: actions/checkout@v3
      - name: Set nightly tag
        run: echo "TAG=nightly-$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build nightly image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ env.TAG }} .
      - name: DockerHub login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push nightly image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ env.TAG }}