name: Test Main-Branch Features

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Unit Tests
        run: mvn test -Dtest=FilmServiceUnitTest
      - name: Run Integration Tests
        run: mvn test -Dtest=FilmServiceIntegrationTest
      - name: Run System Tests
        run: mvn verify -Dtest="FilmServiceE2ETest,FilmServiceRestTest"